file:
  dir: C:/rest/

url:
  app: http://127.0.0.1:5501
#  api: http://127.0.0.1:9989
  py: http://127.0.0.1:5503

  api: http://127.0.0.1:6565

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 30000
  port: 6565
spring:
  http:
    nio: true
  mvc:
    async:
      request-timeout: 30000
  servlet:
    multipart:
      max-file-size: 999MB
      max-request-size: 999MB
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/TestPlace_01
    username: root
    password: hkit301301
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true
        "[user_sql_comments]": true
        "[highlight_sql]": true
        "[hbm2ddl.auto]": update
        #"[implicit_naming_strategy]": "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy" -> ????? ???? ??? ?? ???? ??? ???
    open-in-view: false
    show-sql: true

jwt:
  key: e830642e375b581497a8813547f2349053788666344015003076648701247450